---
title: "test_workflow_doc"
output: pdf_document
params:
  loaded_data:
  sample_info:
  data_file_format:
    label: "Format"
    value: 1
    input: radio
    choices: [1,2,3] 
  no_id_conversion:
    label: "Do not convert to ensembl"
    value: FALSE
    input: checkbox
  min_counts:
    label: "min PCM"
    value: .5
    input: numeric
  n_min_samples_count:
    label: "n libaries"
    value: 1
    input: numeric
  counts_transform:
    label: "Transform counts data for clustering & PCA."
    value: 1
    input: radio
    choices: [edgeR, vst, rlog]
  counts_log_start:
    label: "psuedocount"
    value: 4
    input: numeric
  log_transform_fpkm:
    label: "Log transform?"
    value: TRUE
    input: radio
    choiceNames: ["No", "Yes"]
    choiceValues: [FALSE, TRUE]
  log_start_fpkm:
    label: "Constant c for started log(x+c)"
    value: 1
    input: numeric
  missing_value:
    label: "missing value imputation"
    value: geneMedian
    input: select
    choices: ["geneMedian", "treatAsZero", "geneMedianInGroup"]
  date:
    label: "Date: "
    value: !r Sys.Date()
  printcode:
    label: "Display Code:"
    value: TRUE
    input: checkbox
    
  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = params$printcode)
```

#Print all parameters
```{r}
#print date
cat(params$date)

print(params)
summary(params)
```




```{r}
devtools::load_all()
```

# LOAD DATA FUNCTIONS


## PRE-PROCESS FUNCTIONS

```{r Pre-Process Data }
processed_data <- pre_process(
  data = params$loaded_data,
  missing_value = params$missing_value,
  data_file_format = params$data_file_format,
  low_filter_fpkm = NULL,
  n_min_samples_fpkm = NULL,
  log_transform_fpkm = params$log_transform_fpkm,
  log_start_fpkm = params$log_start_fpkm,
  min_counts = params$min_counts,
  n_min_samples_count = params$n_min_samples_count,
  counts_transform = params$counts_transform,
  counts_log_start = params$counts_log_start,
  no_fdr = NULL
)
```


```{r}
total_counts_ggplot(
  counts_data = processed_data$raw_counts,
  sample_info = params$sample_info
)
```


```{r fig.height=5.5, fig.width=7.5}
colnames(processed_data$data)

eda_scatter(
  processed_data = processed_data$data,
  #plot_xaxis = "p53_IR_1",
  #plot_yaxis = "p53_mock_1"
  plot_yaxis = colnames(processed_data$data)[1],
  plot_xaxis = colnames(processed_data$data)[2]
)
```



```{r fig.height=5.5, fig.width=7.5}
eda_boxplot(
  processed_data = processed_data$data,
  sample_info = params$sample_info
)
```