---
title: "Principal Component Analysis Workflow"
output: html_document
params:
  pre_processed_data:
  pre_processed_descr:
  sample_info:
  pc_x:
  pc_y:
  color:
  shape:
  all_gene_names:
  select_gene_id:
  selected_x:
  selected_y:
  encircle:
  showLoadings:
  pointlabs:
  point_size:
  ui_color:
  ui_shape:
  printcode:
    label: "Display Code"
    value: FALSE
    input: checkbox
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = params$printcode,  warning=FALSE, message=FALSE)
```


```{r include=FALSE}
# load package
library(idepGolem)
```

<!-- This document cannot be knit directly from R studio -->

This html document contains what parameters values were selected on the IDEP interface of the "PCA" tab. It also includes the plots generated from those selections.

# ALL SELECTED PARAMETERS
`r params$pre_processed_descr`


```{r echo=FALSE, message=FALSE, warning=FALSE}
params$pre_processed_descr
```

```{r, include=TRUE}
for (i in 1:length(params)){
  # exclude loaded data & sample info
  if(names(params)[i] != "sample_info" && names(params)[i] != "pre_processed_data" && names(params)[i] != "all_gene_names")
    cat(paste0(names(params)[i], ": ", params[[i]], "\n") )
}
```


## PCA plots

#Principal Component Analysis
```{r}
PCA_plot(
  data = params$pre_processed_data,
  sample_info = params$sample_info,
  PCAx = params$pc_x,
  PCAy = params$pc_y,
  selected_color = params$color,
  selected_shape = params$shape
)
pc_factor_correlation(
  data =  params$pre_processed_data,
  sample_info = params$sample_info
)
```

# T-SNE
```{r}
t_SNE_plot(
  data = params$pre_processed_data,
  sample_info = params$sample_info,
  selected_color = params$color,
  selected_shape = params$shape
  )
```

# Multi-Dimensional Scaling
```{r}
MDS_plot(
  data = params$pre_processed_data,
  sample_info = params$sample_info,
  selected_color = params$color,
  selected_shape = params$shape
)
```


## PCA tools

#Biplot
```{r}
PCA_biplot(
  data = params$pre_processed_data,
  sample_info = params$sample_info,
  select_gene_id = params$select_gene_id,
  all_gene_names = params$all_gene_names,
  selected_x = params$selected_x,
  selected_y = params$selected_y,
  encircle = params$encircle,
  showLoadings = params$showLoadings,
  pointlabs = params$pointlabs,
  point_size = params$point_size,
  ui_color = params$ui_color,
  ui_shape = params$ui_shape
  )
```

# Scree Plot
```{r}
PCA_Scree(processed_data = params$pre_processed_data)
```

# Eigenvalue Correlation
```{r}
# PCAtools_eigencorplot(
#   processed_data = params$pre_processed_data,
#   sample_info =  params$sample_info
#       )
```

