---
title: "Pre_Process Workflow"
output: pdf_document
params:
  loaded_data:
  sample_info:
  data_file_format:
    label: "Format"
    value: 1
    input: radio
    choices: [1,2,3] 
  no_id_conversion:
    label: "Do not convert to ensembl"
    value: FALSE
    input: checkbox
  min_counts:
    label: "min PCM"
    value: .5
    input: numeric
  n_min_samples_count:
    label: "n libaries"
    value: 1
    input: numeric
  counts_transform:
    label: "Transform counts data for clustering & PCA."
    value: 1
    input: radio
    choices: [edgeR, vst, rlog]
  counts_log_start:
    label: "psuedocount"
    value: 4
    input: numeric
  log_transform_fpkm:
    label: "Log transform?"
    value: TRUE
    input: radio
    choiceNames: ["No", "Yes"]
    choiceValues: [FALSE, TRUE]
  log_start_fpkm:
    label: "Constant c for started log(x+c)"
    value: 1
    input: numeric
  missing_value:
    label: "missing value imputation"
    value: geneMedian
    input: select
    choices: ["geneMedian", "treatAsZero", "geneMedianInGroup"]
  scatter_x:
    label: "X axis"
    value: ""
    input: text
  scatter_y:
    label: "Y axis"
    value: ""
    input: text
  date:
    label: "Date: "
    value: !r Sys.Date()
  printcode:
    label: "Display Code"
    value: TRUE
    input: checkbox
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = params$printcode)
```
This pdf documents what parameters values were selected on the IDEP interface. It also includes the plots generated from those selections. 

<!-- This document cannot be knit directly from R studio -->
# Print All Selections
```{r}
for (i in 1:length(params)){
  if( i != 3 && i != 4) # exclude loaded data & sample info
    cat(paste0(names(params)[i], ": ", params[[i]], "\n"))
}
```




```{r, include = FALSE}
devtools::load_all()
#library(idepGolem)
```

# Plots

```{r Pre-Process Data, include = FALSE }
processed_data <- idepGolem::pre_process(
  data = params$loaded_data,
  missing_value = params$missing_value,
  data_file_format = params$data_file_format,
  low_filter_fpkm = NULL,
  n_min_samples_fpkm = NULL,
  log_transform_fpkm = params$log_transform_fpkm,
  log_start_fpkm = params$log_start_fpkm,
  min_counts = params$min_counts,
  n_min_samples_count = params$n_min_samples_count,
  counts_transform = params$counts_transform,
  counts_log_start = params$counts_log_start,
  no_fdr = NULL
)
```


```{r }
total_counts_ggplot(
  counts_data = processed_data$raw_counts,
  sample_info = params$sample_info
)
```


```{r fig.height=5.5, fig.width=7.5 }
eda_scatter(
  processed_data = processed_data$data,
  plot_xaxis = params$scatter_x,
  plot_yaxis = params$scatter_y
  
)
```


```{r fig.height=5.5, fig.width=7.5}
eda_boxplot(
  processed_data = processed_data$data,
  sample_info = params$sample_info
)
```

```{r }
eda_density(
  processed_data = processed_data$data,
  sample_info = params$sample_info
)
```

